### PR TITLE
Version 0.1.6 bump, including a fix for the logstash_home issue

### LINKED ISSUE #9: Syslog plugin have issue with LOGSTASH_HOME variable being missing
From the CI system, syslog is still having problems with the new changes introduced by #3111 in LS core.

error

```
Use `bundle show [gemname]` to see where a bundled gem is installed.
Using Accessor#strict_set for specs
NameError: uninitialized constant LogStash::Environment::LOGSTASH_HOME
    const_missing at org/jruby/RubyModule.java:2723
     pattern_path at /mnt/jenkins/rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/logstash-core-1.5.0.rc4.snapshot2-java/lib/logstash/environment.rb:88
             Grok at /mnt/jenkins/rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/logstash-filter-grok-0.1.10/lib/logstash/filters/grok.rb:217
           (root) at /mnt/jenkins/rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/logstash-filter-grok-0.1.10/lib/logstash/filters/grok.rb:139
          require at org/jruby/RubyKernel.java:1065
          require at /mnt/jenkins/rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /home/jenkins/workspace/logstash_plugin_input_syslog/logstash-input-syslog/lib/logstash/inputs/syslog.rb:1
          require at org/jruby/RubyKernel.java:1065
          require at /mnt/jenkins/rbe
```

More details at http://build-eu-00.elastic.co/view/LS%20Inputs/job/logstash_plugin_input_syslog/165/

### PR DESCRIPTION
**Pull request by purbon**
Fix #9 as in the same way as grok and mutate got fix.

### CODE REVIEW

**Comment by purbon** [comment]
@jsvd @colinsurprenant review on this ?

File: spec/inputs/syslog_spec.rb [hunk 1]
```diff
@@ -1,5 +1,5 @@
 # encoding: utf-8
-require "logstash/devutils/rspec/spec_helper"
+require_relative "../spec_helper"
```
Comment (colinsurprenant) [inline spec/inputs/syslog_spec.rb]: why not require "spec/spec_helper" ?

Comment (purbon) [inline spec/inputs/syslog_spec.rb]: because you want to require your spec_helper, this is not for when your in the conext of the plugin, but for when you run the test in the conext of logstash-core.

Comment (colinsurprenant) [inline spec/inputs/syslog_spec.rb]: I not sure I understand, we do a `require "logstash/devutils/rspec/spec_helper"` in all plugins !?

Comment (purbon) [inline spec/inputs/syslog_spec.rb]: This is a custom spec_helper only for this plugin, same thing is in some other plugins, for example the pattern core.

Comment (colinsurprenant) [inline spec/inputs/syslog_spec.rb]: ah yes, sorry, missed that. ok, so then, why do a custom helper just for this patch? we made the patch directly in the spec file in all the other plugins?

Comment (purbon) [inline spec/inputs/syslog_spec.rb]: I added this, because actually having this fix in the main spec is not nice :-)

Comment (colinsurprenant) [inline spec/inputs/syslog_spec.rb]: so, for a 3 lines fix, you add an extra `require` and an extra file? plus all other fixes are in that file, let's stay consistent. we will have to revisit this soon anyway, no?

Comment (purbon) [inline spec/inputs/syslog_spec.rb]: I particulary find more ugly to add the code in the specs, that you did that before it does not mean i find it nice :+1: ... the usage of spec_helpers for test and move code there is a nice things, the specs should only have specs, not fix/configuration like this ... even if it's just 1 line.

Comment (colinsurprenant) [inline spec/inputs/syslog_spec.rb]: generally speaking yes but specifically here I don't agree, for 3 reasons:
1- the same fix we applied to the 2-3 other plugins are straigth in the main spec file and in this context I think it's better to stay consistent, knowing we will also revisit this patch soon.
2- adding extra structure (1 extra file, plus extra require) is useless for such a small patch.
3- I would argue that this patch is better placed at the top of this spec as it makes it more obvious to understand what is happening. 

of course it would make sense to put it in a helper if there were multiple spec that require that path but it's not the case here and there is no plan to create new spec file in the near future and at that point that patch will have matured and changed.

**Comment by colinsurprenant** [comment]
Thanks! LGTM

File: spec/inputs/syslog_spec.rb (hunk 1 above)
Comment (purbon) [inline spec/inputs/syslog_spec.rb]: Changes updated as you requested.

Comment (colinsurprenant) [inline spec/inputs/syslog_spec.rb]: yay! :fireworks:
